---
title: "Neu4mes"
---

## What is Neu4mes?

Neu4mes project aims to develop a new approach to model and control mechanical system with particular attention to autonomous systems using model-structured neural networks. Robots are rapidly moving out of factories and becoming a part of our everyday lives. To make robots able to cope with unknown situations and environments, the scientific community has largely embraced machine learning to tackle the limits of the analytical modeling approaches. Developing models and controls for autonomous systems need multidisciplinary expertise to overcome potential limitations and risks, such as guaranteeing safety and performance while achieving a high level of autonomy. Using a model-driven approach requires specific expertise for high accuracy, limiting the integration of advanced sensors like lidar, radar, and cameras. Meanwhile, a data-driven approach relies on vast data, lacks performance and safety guarantees due to its black-box nature. Neu4mes addresses this challenge by merging these approaches, using neural networks that base their structure on physical foundations. The project deliberately combines applied mechanics and control theory expertise with machine learning capabilities and flexibility. Neu4mes will study and build the groundwork to demonstrate the potential of this hybrid approach, starting from theory and then applying it to three relevant autonomous system applications: wheel vehicles, quadruped robots, and flying drones. The theoretical and practical knowledge acquired will be summarized and generalized:
-	An open-source framework nnodely released on GitHub under the MIT license will make the power of the hybrid approach immediately accessible to users. nnodely will manage the deployment pipeline for structured neural models and controllers on embedded hardware, interacting with third-party software by a custom application programming interface.	
-	A website in Wikimedia format will collect the knowledge generated during the project and the results obtained within the case studies. The site will be open and serve as an information aggregator on the topic. Neu4mes will provide the scientific and industrial community with a powerful prototyping and deployment tool for structured neural network models and controllers supported by a solid theoretical basis.

## Work with us

### Student's Theses

Theses are available for both bachelor's and master's degrees. The required skills mainly concern mechanical fields of robotics and automation, with particular attention to modeling and control through model-based neural networks. The thesis can be experimental, with hardware platforms such as quadrupeds, manipulators, drones, and scale vehicles available. Additionally, there is the possibility of doing the thesis abroad or in a company. Looks the page for more information.

### PhD Positions

PhD positions will primarily focus on the application of model-structured neural networks for modeling and controlling specific test platforms. In particular, the experimentation will be conducted on quadruped robots, manipulators, drones, and scale vehicles. Another topic of interest for the project concerns the development of a navigation agent for autonomous systems. This agent will be generic and adaptable to different hardware platforms.Send an email for more details.

### Postdoc Positions

Senior positions will involve supervising experimental applications by proposing approaches from other research fields, integrating knowledge from experimental areas into the nnodely framework, and maintaining the website that will collect models and controls developed within the project or found in the state of the art. Positions are sought with both hardware expertise for experimental supervision and mechanical and machine learning expertise for integration into the framework. Send an email for more details.